import Head from 'next/head';
import { coinList } from '../lib/data';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>My Coin Kub</h1>
      </main>

      <div>
        {coinList.map((coin) => (
          <div key={coin.name}>
            <div>{coin.name}</div>
            <div>{coin.coin}</div>
            <div>{coin.cost}</div>
            <div>{coin.value}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
