import Head from 'next/head';
import React, { useState } from 'react';
import { coinList } from '../lib/data';
import { COIN_MOCKUP } from '../lib/coin-mockup';

export default function Home() {
  const [search, setSearch] = useState('');
  const [items, setItem] = useState(coinList);

  useState(() => {
    const getCoinDataItems = coinList.map((v) => {
      const coinInfo = COIN_MOCKUP[`THB_${v.name}`];
      return {
        ...v,
        value: coinInfo.last,
        coin: v.coin
      };
    });
    console.log(
      '🚀 ~ file: index.js ~ line 29 ~ useState ~ getCoinDataItems',
      getCoinDataItems
    );
  }, []);

  const onChangeSearch = (e) => {
    const findArray = coinList.filter((v) =>
      v.name.toLowerCase().includes(e.target.value.toLowerCase())
    );
    setItem(findArray);
  };

  return (
    <div>
      <Head>
        <title>Coin Monitor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
      </Head>

      <div className="py-5 h-screen bg-gray-300 px-2">
        <div className="max-w-md mx-auto bg-gray-100 shadow-lg rounded-lg overflow-hidden md:max-w-lg">
          <div className="md:flex">
            <div className="w-full p-4">
              <div className="relative">
                <input
                  type="text"
                  className="w-full h-12 rounded focus:outline-none px-3 focus:shadow-md"
                  placeholder="Search..."
                  onChange={onChangeSearch}
                />
                <i className="fa fa-search absolute right-3 top-4 text-gray-300"></i>
              </div>
              <div>{process.env.environment}</div>
              {items.map((coin) => (
                <ListMyCoinItem key={coin.name} {...coin} />
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function ListMyCoinItem({ name, value, coin, cost, image }) {
  return (
    <ul>
      <li className="flex justify-between items-center bg-white mt-2 p-2 hover:shadow-lg rounded cursor-pointer transition">
        <div className="flex ml-2 items-center flex-1">
          <img src={image} width="30" className="rounded h-8" />
          <div className="flex flex-col ml-2">
            <span className="font-medium text-black">{name}</span>
            <span className="text-sm text-gray-400 truncate w-32">
              Cost: {cost.toLocaleString()}
            </span>
            <span className="text-sm text-gray-400 truncate w-32">
              Avail: {coin}
            </span>
            <span className="text-sm text-gray-400 truncate w-32">
              THB: {value.toLocaleString()}
            </span>
          </div>
        </div>
        <div className="flex flex-col items-center">
          <span className="text-green-400">+{coin.toLocaleString()}฿</span>
        </div>
      </li>
    </ul>
  );
}
