import Head from 'next/head';

export default function Management() {
  return (
    <div>
      <Head>
        <title>Coin Monitor - Management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Management</h1>
      </main>
    </div>
  );
}
